Repository 7map/7map, pull requests merged in 2021-05, with the labels that each got.

#48 Incorporate gui library
  .factorypath
  .gitignore
  pom.xml
  src/main/java/com/sevenmap/App.java
  src/main/java/com/sevenmap/Demo.java
  src/main/java/com/sevenmap/exceptions/IncorrectChildTypeError.java
  src/main/java/com/sevenmap/ui/Engine.java
  src/main/java/com/sevenmap/ui/Window.java
  src/main/java/com/sevenmap/ui/elements/Camera.java
  src/main/java/com/sevenmap/ui/elements/GeomNode.java
  src/main/java/com/sevenmap/ui/elements/GuiLayer.java
  src/main/java/com/sevenmap/ui/elements/GuiNode.java
  src/main/java/com/sevenmap/ui/elements/Item.java
  src/main/java/com/sevenmap/ui/elements/Node.java
  src/main/java/com/sevenmap/ui/elements/RootNode.java
  src/main/java/com/sevenmap/ui/gfx/GuiRenderer.java
  src/main/java/com/sevenmap/ui/gfx/SceneRenderer.java
  src/main/resources/fonts/Raleway/OFL.txt
  src/main/resources/fonts/Raleway/README.txt
  src/main/resources/fonts/Raleway/Raleway-Italic-VariableFont_wght.ttf
  src/main/resources/fonts/Raleway/Raleway-VariableFont_wght.ttf
  src/main/resources/fonts/Raleway/static/Raleway-Black.ttf
  src/main/resources/fonts/Raleway/static/Raleway-BlackItalic.ttf
  src/main/resources/fonts/Raleway/static/Raleway-Bold.ttf
  src/main/resources/fonts/Raleway/static/Raleway-BoldItalic.ttf
  src/main/resources/fonts/Raleway/static/Raleway-ExtraBold.ttf
  src/main/resources/fonts/Raleway/static/Raleway-ExtraBoldItalic.ttf
  src/main/resources/fonts/Raleway/static/Raleway-ExtraLight.ttf
  src/main/resources/fonts/Raleway/static/Raleway-ExtraLightItalic.ttf
  src/main/resources/fonts/Raleway/static/Raleway-Italic.ttf
  src/main/resources/fonts/Raleway/static/Raleway-Light.ttf
  src/main/resources/fonts/Raleway/static/Raleway-LightItalic.ttf
  src/main/resources/fonts/Raleway/static/Raleway-Medium.ttf
  src/main/resources/fonts/Raleway/static/Raleway-MediumItalic.ttf
  src/main/resources/fonts/Raleway/static/Raleway-Regular.ttf
  src/main/resources/fonts/Raleway/static/Raleway-SemiBold.ttf
  src/main/resources/fonts/Raleway/static/Raleway-SemiBoldItalic.ttf
  src/main/resources/fonts/Raleway/static/Raleway-Thin.ttf
  src/main/resources/fonts/Raleway/static/Raleway-ThinItalic.ttf
Labels: dependencies, rendering

#51 feat(rendering): add Gui Demo with GuiNode subclass
  pom.xml
  src/main/java/com/sevenmap/Demo.java
  src/main/java/com/sevenmap/spinel/elements/PrototypeGuiN.java
Labels: enhancement, rendering

#49 Implement basic collider node system
  src/main/java/com/sevenmap/Demo.java
  src/main/java/com/sevenmap/spinel/elements/Camera.java
  src/main/java/com/sevenmap/spinel/elements/GeomNode.java
  src/main/java/com/sevenmap/spinel/elements/RootNode.java
  src/main/java/com/sevenmap/spinel/elements/colliders/Collider.java
  src/main/java/com/sevenmap/spinel/elements/colliders/PlaneCollider.java
  src/main/java/com/sevenmap/spinel/elements/colliders/RayCollider.java
  src/main/java/com/sevenmap/spinel/gfx/SceneRenderer.java
Labels: rendering

#44 adding the last version of the logger class
  src/main/java/com/sevenmap/App.java
  src/main/java/com/sevenmap/logger.java
  src/main/java/com/sevenmap/spinel/utils/Color.java
  src/test/java/com/sevenmap/ui/maths/Vector3fTest.java
Labels: enhancement
